name: deploy-test
on:
  #push:
    #branches:
      #- main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy CDK stacks to test
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::683578897984:role/aws-gh-oidc
          aws-region: us-east-1
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: install npm 2
        run: npm i -g npm && npm ci

      - name: Install AWS CDK
        run: 'sudo npm install -g typescript && sudo npm install -g ts-node'

      - name: Install AWS CDK 2
        run: 'sudo npm install -g aws-cdk && sudo npm install -g aws-cdk-lib'
     
      - name: CDK Synth
        run: cdk synth GithubOidcStack
        working-directory: ./

      - name: CDK Deploy
        run: cdk deploy --require-approval never GithubOidcStack
        working-directory: ./